### PR TITLE
Simple menu 12

### LINKED ISSUE #12: Add a menu to the program
### What do you want to see?

When the program is run. A menu should be visible.
The following options should be displayed. 

1. Log attendance
2. View attendance
3. Reset attendance

After this, the user can enter 1,2 or, 3 to move to the next section.

If the code for 2 and 3 are not implemented yet, you can directly return.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by abhiraj2**
**Brief Description of Fix**

Added a simple CLI menu which takes one of three options 1,2,3

**Linked Issue**  
Closes #12 (Replace with Issue number)

I have already commented on the issue to be assigned but no action was taken and since time is running out, I have to make this pull request

### CODE REVIEW

**Comment by anirudhRowjee** [comment]
Hi! Your PR doesn't show the attendance recorded, but just prints a single line.
Please take care of this.

**Comment by abhiraj2** [comment]
since the issue was just for the menu, I only added placeholder functions
I have created seperate PRs for those functionalities as well
Please check

**Comment by anirudhRowjee** [comment]
Fair enough. LGTM

**Comment by anirudhRowjee** [comment]
!bounty 30

**Pull request merged**
