### PR TITLE
Added epoch time.

### PR DESCRIPTION
**Pull request by Skanda-Prasad**
I've added epoch time and also made the program display the date and time before the user gives input to it.

### CODE REVIEW

**Comment by Skanda-Prasad** [comment]
I've added all the the new features you've asked. I hope that they are all displayed and there aren't any logical errors. Thank you!

**Comment by anirudhRowjee** [comment]
this is what the output shows me :(

**Comment by Skanda-Prasad** [comment]
Thank you!!!

**Comment by Skanda-Prasad** [comment]
Made the changes. Please check and let me know if I need to do anything else.

**Comment by Skanda-Prasad** [comment]
> You can use `fmt.Sprint()` instead of trying to convert to a string. It's printing a rune otherwise.

Used 'fmt.Sprint()'

I think I may have figured out how to add the human readable time too. I've added it. Please check it.

**Comment by anirudhRowjee** [comment]
Looks good to me! Output works.

**Comment by Skanda-Prasad** [comment]
YES!!! Finally!

**Comment by Skanda-Prasad** [comment]
Thank you!!!

**Comment by anirudhRowjee** [comment]
Yes, it did

**Comment by Skanda-Prasad** [comment]
Not trying to be greedy but, am I eligible for the extra bounty points assigned to it? This is a competition and I want to go to the best position possible by me. I hope you don't mind me asking this.

**Comment by anirudhRowjee** [comment]
!bounty 60

**Pull request merged**
